spring:
  applicaton:
    name: finex-trade
  datasource:
    url: jdbc:postgresql://finex-database.ciejfzld0efh.us-east-2.rds.amazonaws.com/finex
    username: postgres
    password: postgres
  jpa:
    generate: true
    properties:
      hibernate:
        jdbc:
          non_contextual_creation: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${FINEX_DISCOVERY_URI}
  instance:
    preferIpAddress: true
    ip-address: ${FINEX_DISCOVERY_CLIENT_IP}
  fetchRegistry: true

