spring:
  applicaton:
    name: finex-orderbook
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8443
  ssl: 
    enabled: true
    key-store: ${TLS_KEYSTORE}
    key-store-password: ${TLS_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

eureka:
  client:
    serviceUrl:
      defaultZone: ${FINEX_DISCOVERY_URI}
  instance:
    preferIpAddress: false
    hostname: ${FINEX_DISCOVERY_CLIENT_HOSTNAME}
  fetchRegistry: true
