spring:
  applicaton:
    name: finex-trade
  datasource:
    url: jdbc:postgresql://127.0.0.1/finex
    username: postgres
    password: postgres
  jpa:
    generate: true
    properties:
      hibernate:
        jdbc:
          non_contextual_creation: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 8443
  ssl: 
    enabled: true
    key-store: ${TLS_KEYSTORE}
    key-store-password: ${TLS_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

eureka:
  client:
    serviceUrl:
      defaultZone: ${FINEX_DISCOVERY_URI}
  instance:
    preferIpAddress: false
    hostname: ${FINEX_DISCOVERY_CLIENT_HOSTNAME}
  fetchRegistry: true

